### ISSUE TITLE
Hooking to Task/Creation/Modification

### ISSUE THREAD

**Issue by creecros** [creecros/MetaMagik#1]
After playing with this, I determined, it is beyond my capabilities to easily hook this to Task Creation/Modification. Why? A lot of reasons, but mainly, once you open the task edit modal, you are playing with Task Table and Task related controllers. I don't know how to build relationships in the TaskModels to a dynamic set of Key's that could exist in the Metadata Table. Simply put, once you hit "Save", I have no idea how to update the values for the Metadata since it doesn't exist in the TaskModel. Pretty sure there is another solution, or even a better one, but I am just a novice here to be honest.

Solution would be to hook to task layout, just above "Description" and use a seperate Modal to edit metadata. This would be similiar to curren plugin, but i would add it to the main layout when you view a task, and it would be editable via a Modal, like how "Edit Task" currently is.

**Comment by creecros** [comment]
well, maybe i can figure this out.

**Comment by TheCloud** [comment]
These days I was over-charged and I couldn't check the code, anyway we can ask for help :-)

**Comment by creecros** [comment]
I got them on there as editable fields, now I just need to figure out how to save them, pretty sure it will require me to replace the Models for Task Creation/Modification/Duplication. Using "Tags" as a reference on how to do it, as I notice that each model has an "UpdateTags" function, so I'll just need to do the same for the MetaData. Currently it doesn't know where to save the data, but it can read it.

![image](https://user-images.githubusercontent.com/26339368/45380917-e33cb900-b5d1-11e8-9f8f-178bb86ea407.png)

**Comment by creecros** [comment]
also, i'm working under the "test" branch

**Comment by creecros** [comment]
Success, I got it.

**Comment by creecros** [comment]
That wil be the idea, but not implmented yet. Baby steps, 1 issue at a time.

**Comment by creecros** [comment]
If you check the project board, you'll see where I am at on the to do list and what I'm still working on. Although I solved this, I still need to implement this principle into task create and duplication, followed by a whole slew of other things.
