### ISSUE TITLE
Meta should application wide or project wide ?

### ISSUE THREAD

**Issue by TheCloud** [creecros/MetaMagik#10]
Currently only Kanboard admins can add new meta fields, and when admin do so, all projects's tasks are affected.

I think that a Project Owner should have the same functionality but "project wide" only, in this way only his project's tasks are affected.

So basically you can have:
=> Application wide task's metadata
=> Project wide task's metadata

Please note that it's always about tasks's metadata that I'm referring to, not project's metadata or user's metadata

**Comment by creecros** [comment]
Yes, this would be nice, but would take a lot of code alteration I believe, not even 100% sure it's feasible without creating a table, because meta data table has basically three fields, id, name and value. I'd have to look into it.

**Comment by creecros** [comment]
To explain, there isn't a field to hold a project_id

**Comment by creecros** [comment]
I think for now, I'm good on this. It will be a lot of work to put this in, something I could perhaps revisit later down the road. I'll leave this open as a reminder.

**Comment by creecros** [comment]
another note - the settings panel would never be accessible to anyone that isn't an admin, so a new config menu would have to be added into projects config.

**Comment by tjdm007** [comment]
I understood. the metada extension is incompatible.
I deleted it and everything is ok ..

**Comment by creecros** [comment]
Moved to separate issue #29

**Comment by Ryonez** [comment]
Defiantly would like to see this. Currently while nice, I can't use it because I plan to have projects that wouldn't make sense to have fields from all the others.

**Comment by creecros** [comment]
Its been requested a few times, and its on my long list of to dos.

**Comment by Ryonez** [comment]
They never seems to end do they...

It's all good though, I'll keep an eye out for updates, cheers.

**Comment by creecros** [comment]
Was easier than i anticipated.

**Comment by Ryonez** [comment]
> 
> 
> Was easier than i anticipated.

Good to hear, thank you for adding that in!
