### ISSUE TITLE
spaces are getting converted to _ for field names going into metadata table.

### ISSUE THREAD

**Issue by creecros** [creecros/MetaMagik#12]
I forgot to fix this, putting on my to do list for next release.
For now, just don't use spaces in field names.

**Comment by creecros** [comment]
can't seem to figure out where this is happening, it's somewhere in the app and not the plugin. my only current solve would be to convert spaces in the metadatatype table, which is already done actually, and saved as machine_name, so just replace all human_name with machine_name would solve it. 

not a fan of this solve though, so if someone can find where it happens, more power to them.

**Comment by creecros** [comment]
for now added an error if spaces are used, and simply won't allow a field name to contain spaces.

**Comment by santhosh2kece** [comment]
Hi creecros, Thank you for this wonderful plugin. I can now create custom fields with space in it.
I will need to to export the custom fields using API and hence I will like to know what will be the field name be like while exporting using API. 

Will it be  actual field name with a space. Example "Field Name" or will it have a underscore in between the field name like "Field_Name". kindly clarify.

**Comment by creecros** [comment]
"Field Name"

pretty sure.
