### ISSUE TITLE
some strings are not translatable

### ISSUE THREAD

**Issue by BlueTeck** [creecros/MetaMagik#15]
Some strings are not translatable i.e.:

https://github.com/creecros/MetaMagik/blob/b127457bc32513761cf42698d4cb1dcb83beeb89/Template/config/metadata_types.php#L40-L43

**Comment by creecros** [comment]
Ah, should probably be t('text') code. I'll take care of it tonight.

**Comment by creecros** [comment]
Now translatable, double check my German translations before I update release.

**Comment by BlueTeck** [comment]
They are fine :)
