### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by kenlog** [creecros/MetaMagik#17]
Hello creecros, updating to the latest version from the plugin directory, it returns me not found plugin.

**Comment by creecros** [comment]
Github had some issues last night, hopefully it will resove itself, but the link is accurately defined:
https://github.com/kanboard/website/blob/dafbf7a878c6f3412743a5f8de373dcce7ed2522/plugins.json#L86-L96

**Comment by creecros** [comment]
github is all whacked out right now. it should work once they resolve
issues.

**Comment by creecros** [comment]
I just realized this is MetaMagik and not Customizer.

**Comment by creecros** [comment]
And it too is fine:
https://github.com/kanboard/website/blob/dafbf7a878c6f3412743a5f8de373dcce7ed2522/plugins.json#L458-L469

Must be github.

**Comment by kenlog** [comment]
Perfect thanks! :+1:
