### ISSUE TITLE
Repositioning of displayed values

### ISSUE THREAD

**Issue by kenlog** [creecros/MetaMagik#21]
it would be great, ordering the metadata in the task

**Comment by creecros** [comment]
shouldn't be an issue, have a busy week at work, but i'll take a look next chance i get.

**Comment by creecros** [comment]
Task Creation/Modification 
or 
Task Details
or Both?

**Comment by kenlog** [comment]
Yes, in fact it is better both. :+1:

**Comment by kenlog** [comment]
forgive me, it is better with this addition but I wanted to drag the values to order them manually such as for example with the "Sub-Tasks".

**Comment by creecros** [comment]
Oh, I misunderstood. I'll have to do some research on that one, and figure it out.

**Comment by kenlog** [comment]
I took a look, we need to make some additions to the code more or less simple.

**Comment by creecros** [comment]
are you wanting to save the positions? That might be difficult, since we are using metadata and it only stores kay => value

**Comment by kenlog** [comment]
in fact, you need the ID to manage the sorting

**Comment by creecros** [comment]
k, here's the solution:

Add position_id to the metadata_types table
Remove all other metadata not defined as a type from the summary accordian (been meaning to do that anyway)

however,

the positions will not be task dependent

**Comment by creecros** [comment]
that took brain power

**Comment by kenlog** [comment]
@creecros now it's perfect! Thank you very much

**Comment by creecros** [comment]
Just noticed I forgot to apply the sort to the tooltip.
