### ISSUE TITLE
Metadata can be removed by viewer

### ISSUE THREAD

**Issue by Gold-Wings** [creecros/MetaMagik#30]
A user with a "Project Viewer" role can edit or remove metadata in the board view and in the task view.
Is this a normal behavior?
My opinion is that a viewer user should not have any possibility of modification.

**Comment by creecros** [comment]
@Gold-Wings 

- Removed all access for Project Viewers in every controller related to modify. 
- Removed Project Viewers ability to See the Metadata Sidebar or Tooltip
- Project Viewers can still export tasks to CSV which will include custom fields.

**Comment by Gold-Wings** [comment]
Thank you for the modifications! :-) :+1:

**Comment by Gold-Wings** [comment]
I didn't realize your modification was preventing any access to the metadata.
Is there a possibility that viewers could see the metadata? (without the possibility to modify them of course)

**Comment by creecros** [comment]
Ya, that's possible too. But, more of a preference, might add a toggle. Let me think on it.

**Comment by creecros** [comment]
https://github.com/creecros/MetaMagik/releases/tag/1.2.2

For now, I'll just do it your way, and if anyone disagrees in the future, I'll add a toggle.

**Comment by Gold-Wings** [comment]
Once again, thank you very much for the changes, it's great!
It works perfectly for me and is well suited for my use.
