### ISSUE TITLE
question

### ISSUE THREAD

**Issue by sstecker** [creecros/MetaMagik#33]
are the  custom fields available thru the api for inserts/read?

**Comment by creecros** [comment]
No, I'd have to look into that, but off the top of my head, I'm thinking that might not be plausible. Stay tuned, on Xmas vaca, I'll look next chance I get.

**Comment by sstecker** [comment]
> No, I'd have to look into that, but off the top of my head, I'm thinking that might not be plausible. Stay tuned, on Xmas vaca, I'll look next chance I get.

thank you for quick response.  do not worry,  this was not a request.  im planning an upgrade to our erp/kanboard integration over xmas and researching how to get done what i want to change.  i didnt see any api mention in docs so just wanted clarification.

**Comment by creecros** [comment]
No worries, I did take a look, and think I can implement, not sure when I'd get around to it though. It'd be a nice feature.
