### ISSUE TITLE
meta dropdown field not being copied when task is duplicated to another project

### ISSUE THREAD

**Issue by rukunpuc** [creecros/MetaMagik#36]
I have a dropdown field called "Category" with the options government, semi-government and local. For example a task has been created with the meta field " Category" with the option selected Government. Now when I am going to duplicate the task to another project , no options are being shown in dropdown during the duplication procedure pop up. But after the task is duplicated, the meta dropdown field options can be found in the edit task panel.

**Comment by creecros** [comment]
Because, duplication and duplication to another project, use different models. I never accounted for the later. I'll put on my to do list.
