### ISSUE TITLE
Filter remembers previous value

### ISSUE THREAD

**Issue by jeromg** [creecros/MetaMagik#42]
Hi there,

I'm using Kanboard 1.2.10 with Metamagik 1.3.

Repro :
  1. Create one custom field "Manager" (of type 'text') with scope restricted to 'Project A' 
  2. Add the value "John" for task 1 
  3. Filter Project A tasks using: metaval:"John", task 1 shows up (as expected)
  4. Edit task 1 and change value from "John" to "Paul"
  5. Filter Project A tasks using: metaval:"Paul" -> task 1 shows up (as expected)
  6. Filter Project A tasks using: metaval:"John" -> task 1 still shows up (**NOT** expected)

I've restarted php-fpm and nginx on my server (just in case) to no avail.

Hope that helps.

Cheers  /jerome

**Comment by creecros** [comment]
Tested. Not reproducible.

**Configuration**
```
Application version: v1.2.10
PHP version: 7.3.6
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 4.9.45-rancher
Database driver: sqlite
Database version: 3.28.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
```
