### ISSUE TITLE
DB Field Usage

### ISSUE THREAD

**Issue by githubetc** [creecros/MetaMagik#43]
Thanks for giving us a hint on how to use the DB field inside MetaMagik:
tablename, keycolumn, valuecolumn

By making keycolumn the SAME as valuecolumn I can now list out all values in that column :)
But it does not seem to work if the two column names are DIFFERENT :(
 
Can you please explain when we can use different column names ?
May be we can select only certain values instead of all values in a column ?

Thanks for your help.

This references Closed Issue #29 
> Yeah, that's a tricky one, you can break things if you get it wrong.
> 
> groups,name,name
> 
> Would give you a drop down of all groups.

**Comment by creecros** [comment]
Give your example.

**Comment by githubetc** [comment]
Say for the "columns" table in kanboard, I want a drop down field showing "title" column values based on "project_id" column value equals a certain value.

So with the DB field format
tablename, keycolumn, valuecolumn
instead of using
columns, title, title
which will list ALL values in the "title" column.

Is it possible to use
columns, project_id=5, title
which will list only values if "title" belonging to "project_id=5"

I guess I am not sure about the difference between keycolumn and valuecolumn.
When do we use different column names for keycolumn and valuecolumn ?
Are they always the same ?

Thanks for your help.

**Comment by creecros** [comment]
Not gonna lie, I didnt incorporate this feature, not really used it much. I'll take a look though and see if I can make it work as requested.

**Comment by creecros** [comment]
Although, now that I re read the question, I'm still not sure what your looking for. My thought would be key column should be what you see in the dropdown, valuecolumn should be the set of values.. So, I'll take a deep look at it the feature, and report back its usage,  and then we can go from there.

**Comment by creecros** [comment]
@githubetc So, after playing with it, it does not seem to work the way I would expect it to. Next chance I get, I'll improve, and possibly add a field to address your need. No timetable though.

**Comment by githubetc** [comment]
Thanks for investigating the issue and improving it.

Something general that supports ability to select only rows with a certain column value 
e.g. "project_id=5" as discussed above
will be extremely useful.

Not sure what is the best way for me to contribute.
Will a donation of say US$200 be proper or even enough for such an improvement ?

**Comment by creecros** [comment]
Donations are always welcome and very grateful for them. Whatever you feel comfortable donating. I'll take care of this tomorrow for you.

**Comment by githubetc** [comment]
I have donated US$200 via the donate button (it went through paypal).
Thanks for your help with this.

**Comment by creecros** [comment]
@githubetc 

https://github.com/creecros/MetaMagik/releases/tag/1.4.0

Give her a test drive. Let me know if you have any issues.

To produce your result, per your request, choose the new field type, `Column from DB, based on equals Criteria`

in the options, and this is an example, enter: `tasks,project_id,5,title`

this would provide a list of all task titles in the project with the id 5.

**Comment by creecros** [comment]
Also, i appreciate the donation, Thank you!
