### ISSUE TITLE
Custom field value shows up twice in task summary when used in different projects

### ISSUE THREAD

**Issue by YohannLYD** [creecros/MetaMagik#48]
If I create two or more non-global custom fields of the same name, they show up multiple times in the task summary. It seems to be alright on the edit task part.

In my particular case, I have the __DCP__ field that is associated with the projects 20 and 24. They are declared in the settings part of kanboard :
![image](https://user-images.githubusercontent.com/8319299/70708237-556ee280-1cda-11ea-849a-89d260c211ed.png)

If I fill this field in any task, it ends up showing up twice :
![image](https://user-images.githubusercontent.com/8319299/70708410-b4ccf280-1cda-11ea-8f0c-25d8c29de603.png)

Considering that I will definitely use this field for upcoming projects, it's gonna add up each time I will associate it to additional projects...

I think the bug could be fixed somewhere around the [task template/custom field loop](https://github.com/creecros/MetaMagik/blob/master/Template/task/metatable.php) but I am no PHP fluent enough to do it on my own.

**Comment by creecros** [comment]
I should have some time before the holidays to take a look.

**Comment by YohannLYD** [comment]
After investigating the issue, I think the bug can be solved somewhere around how the metadata are rendered on the task's summary.

It seems that the summary only relies on the __task\_has\_metadata__ table to check if there are metadata to show. It's not using the __attached\_to__ field in the __metadata\_types__ table to make sure which information has to be shown on the summary.

I made changes on `Template/task/metasummary.php` by filtering the fields to display with getAllInScope() instead of getAll(). It seemed that it fixes the issue.

See PR #51

**Comment by creecros** [comment]
oversight on my part i guess, thanks for PR.
