### ISSUE TITLE
Field label

### ISSUE THREAD

**Issue by ivolvicente** [creecros/MetaMagik#49]
Hello, 

How can i add a more readable text for my custom field? For me it's no a problem, but users tend to dislike name_like_this.

**Comment by creecros** [comment]
You'd have to think outside the box. Theres not a short answer, but it could be done through conversions into the DB, and then convert back out. Long story short, no spaces allowed, but you could, per say, converts spaces to some sort of character set, and then re convert when you display it.

**Comment by creecros** [comment]
@ivolvicente 

Was able to figure this out in a simple manner by adding a property and `'beauty_name'` and converting all the underscores to Spaces. Then used that new property only when displaying field labels. So, it wasn't too difficult, and I could merge, but want to make sure you still want this.

**Comment by ivolvicente** [comment]
Hi @creecros 

Thanks for the effort implementing this enhancement, saddly for the moment i stopped my R&D (company pivoted on the project).

But i belive it's a valid enhancement for other people, it deserve to be merged :wink:
