### ISSUE TITLE
Make Custom created field as Required"" field while creating tasks

### ISSUE THREAD

**Issue by santhosh2kece** [creecros/MetaMagik#50]
Hi, 

I downloaded Metamagik plugin for creating custom fields and this plugin works, however there is an issue with the "required" fields for creating task.

While creating custom fields, there was a checkbox called "required" and I believe that if the custom fields are having the "required"check box checked, then it will become a mandatory field while creating a task. This mandatory field check doesn't work and we can create a task without filling an data in the custom fields
![Metamagik_Custom_field](https://user-images.githubusercontent.com/55787227/72866495-eaf78c00-3cf4-11ea-9c38-e15a8196034f.png)
.

**Comment by creecros** [comment]
same issue as #45

**Comment by creecros** [comment]
Thanks, I'm aware. One of these days I'll look into a fix.

**Comment by santhosh2kece** [comment]
Thank you. Appreciate your response.

**Comment by Markus-** [comment]
Is there anything new.
The * is shown for text fields, bit is not enforced. Is there any way to enforce required fields?

**Comment by creecros** [comment]
yes, there is a way. I just havent had the time to look into it. Last time I tried working on this, i spent over an hour and couldn't solve it, so, its just a matter of getting the time required.

**Comment by creecros** [comment]
@Markus- 

Master is updated for testing. Let me know if you experiences any issues.

**Comment by Markus-** [comment]
Hopefully I can test this at the weekend. Have to finish this during the next 2-3 weeks, so good chances. I'll keep you informed.

Regards
Markus

**Comment by Markus-** [comment]
I just downloaded the Code as zip and unzipped it under plugins. Code is in place, but it does not work as expected.

I thought, creating a new field (I tested a text field) and ticked the "required" box lead to following behavior
 - creating a task without populating any value to the field gives an error
 - input some text into the field allows saving the task

Regards
Markus

**Comment by creecros** [comment]
just to confirm, you restarted your server? if you previously had metamgik installed, the original code could be cached.

**Comment by Markus-** [comment]
No of course not ;)
After restarting it works as designed. Quickly tried to creating and changing a task with the text field and everything works now. Thanks.

Regards
Markus

**Comment by santhosh2kece** [comment]
Thanks ceecros, it worked.
