### ISSUE TITLE
Get metadata key and values

### ISSUE THREAD

**Issue by amnan181** [creecros/MetaMagik#53]
how we can get metadata key and values?

**Comment by creecros** [comment]
from where are you looking? is there context you can provide? Are you looking for the table? What exactly is it you are trying to do?

**Comment by amnan181** [comment]
Can you give me example how we can get data from task_has_metadata with task id?

**Comment by BlueTeck** [comment]
https://docs.kanboard.org/en/latest/plugins/metadata.html

**Comment by amnan181** [comment]
I have check this but its giving undefined taskMetadataModel

**Comment by amnan181** [comment]
I want to call this in task file where task code is showing

**Comment by BlueTeck** [comment]
Could you share your code?

**Comment by amnan181** [comment]
I am calling this function in private_task file but its giving undefined. We cannot call this function in other files?

**Comment by amnan181** [comment]
![task](https://user-images.githubusercontent.com/44324439/76951121-fbab3380-692c-11ea-95bd-d8161de4eab5.PNG)

**Comment by amnan181** [comment]
here is my code

**Comment by creecros** [comment]
From a template, you must use, $this->task->....
i.e.
https://github.com/creecros/MetaMagik/blob/90a5d8152659af5827140099adf7189212880fad/Template/task/metasummary.php#L3

**Comment by amnan181** [comment]
Thank you so much sir
