### ISSUE TITLE
Longer text and text size limit in form

### ISSUE THREAD

**Issue by sulazix** [creecros/MetaMagik#54]
Thanks a lot for this incredible plugin ! 

It could be great to be able to add "textarea" type field with MD support, the standard "text" field is quiete short and not readable friendly for long text.

Maybe also add a size="..." or maxlength="..." in form attribute for text field to limit size of text in form to be equal with the DB size limit 

Best regards,
Robin

**Comment by cjohnsonuk** [comment]
+ 1 for text area.  I'm trying to record "Recognised Risks" and "Measures to Address Known Risks" against each task.  Ideally this would be in a table format to match up each risk with how we are dealing with it and be able to add as many of these pairs as required like comments are added.  Until this is possible having text areas where we can add one risk per line is an acceptable interim.

**Comment by creecros** [comment]
537ffba541ea6c5b71f44b1d3c9e4f1dfabe4d93

added textarea.

**Comment by creecros** [comment]
feature added. textarea is now a field "type" and markdown will be applied on the summary/details page of the task, but not when editing. There is no min/max limit.
