### ISSUE TITLE
extend the types of data available

### ISSUE THREAD

**Issue by alaner2k** [creecros/MetaMagik#56]
Hi creecros!
Tks for your super plugin / it allows to tune the kanboard just for me.
However I wonder why the plugin doesn't allow to use not just a DATE but DATE+TIME field (like a "due date" for a task)?
I tried to modify the field type in the DB directly but in this case I can's see the modified field in the task view at all :-(

If by chance you can add this feature to your plugin it would extend our practice :-)

Thanks anyway for your time & knowledge!

**Comment by creecros** [comment]
Should be very easy. Change the input type, from "date" to "datetime-local" in the MetaHelper.

**Comment by alaner2k** [comment]
Tks a lot for the direction / frankly I'm not a programmer thus I attempted to change the field "data_type" @ table "metadata_types" from DATE to DATETIME or DATETIME-LOCAL by PHPMyAdmin in the DB, but with no success...
Well hope the MetaHelper will help :-)

**Comment by creecros** [comment]
This line, specifically 
https://github.com/creecros/MetaMagik/blob/90a5d8152659af5827140099adf7189212880fad/Helper/MetaHelper.php#L30

**Comment by alaner2k** [comment]
Lovely!!!
I managed to re-define the date to date&time :-)
same time I tried not just re-define but ADD the new format by copying the function renderDateField, unfortunately with no further success yet :-)
Anyway you assisted my a lot!!! Thank you again!

**Comment by creecros** [comment]
If you want to add it, you would have to add the type as well, by defining it in the model and add the option in the template. It wouldn't be hard, but there is more to it than meets the eye.

**Comment by alaner2k** [comment]
IT
WORKS
PERFECTLY
!
Thanks for your efforts!
