### ISSUE TITLE
Tooltip is not displayed in Board view

### ISSUE THREAD

**Issue by oliviergenest** [creecros/MetaMagik#57]
After proper installation of MetaMagik v1.4.4 through the Extensions GUI, I am able to create and put values in custom fields.
However, in the Board view, the tooltip is not visible and therefore does not allow to quickly see values.
See screenshot showing that the value for custom field "Montant" is set:
![image](https://user-images.githubusercontent.com/47632278/95059958-e5fb3100-06f9-11eb-955e-0511507af599.png)
See screenshot showing that the tooltip is not available:
![image](https://user-images.githubusercontent.com/47632278/95059984-f27f8980-06f9-11eb-9217-5b7d729fd764.png)

Thanks for your help

**Comment by creecros** [comment]
Can you copy paste your configuration for kanboard.

**Comment by oliviergenest** [comment]
You mean the config.php file?
Here it is:
```
<?php
define('DEBUG', true);
define('ENABLE_URL_REWRITE', true);
define('PLUGIN_INSTALLER', true);
define('PLUGIN_API_URL', 'https://raw.githubusercontent.com/kanboard/website/master/plugins.json');

// Mail transport to use: "smtp", "sendmail" or "mail" (PHP mail function)
define('MAIL_FROM', '<username>@<domain>.com');
define('MAIL_TRANSPORT', 'smtp');
define('MAIL_SMTP_HOSTNAME', 'smtp.<domain>.com');
define('MAIL_SMTP_PORT', 465);
define('MAIL_SMTP_USERNAME', '<uername>@<domain>.com');
define('MAIL_SMTP_PASSWORD', '<password>');
define('MAIL_SMTP_ENCRYPTION', "ssl"); // Valid values are "null", "ssl" or "tls"
define('MAIL_SENDMAIL_COMMAND', '/usr/sbin/sendmail -bs');

// Database driver: sqlite, mysql or postgres (sqlite by default)
define('DB_DRIVER', 'mysql');
define('DB_USERNAME', '<username>');
define('DB_PASSWORD', '<password>');
define('DB_HOSTNAME', '<hostname>');
define('DB_NAME', '<dbname>');

// Enable/disable remember me authentication
define('REMEMBER_ME_AUTH', true);
define('SESSION_DURATION', 0);
```

**Comment by creecros** [comment]
No, I mean system config.
![Screenshot_20201005-110727_Chrome](https://user-images.githubusercontent.com/26339368/95097037-02e43400-06fb-11eb-96d6-25f178fc7def.jpg)

**Comment by creecros** [comment]
I meant system config
![20201005_110910](https://user-images.githubusercontent.com/26339368/95097325-59517280-06fb-11eb-8b1c-8b9129c640eb.jpg)

**Comment by oliviergenest** [comment]
Sorry, here it is:
![image](https://user-images.githubusercontent.com/47632278/95120579-140a6080-074e-11eb-8492-0575978df79c.png)

**Comment by creecros** [comment]
just tested, works fine.
![image](https://user-images.githubusercontent.com/26339368/95142856-ac9ae380-0742-11eb-9476-e3389620904d.png)
I see you have other plugins installed, like the thumbs up thumbs down voting plugin, there is probably a conflict.

**Comment by oliviergenest** [comment]
I tried to remove the TaskVote plugin but it still does not work.
I will try with other plugins... And move to a fixed version installation (instead of master) as you suggested.
I will keep you informed if I find the root cause of the issue.

**Comment by creecros** [comment]
Take a screenshot of your plugins page, and I can take a look and see if I can find the conflict.

**Comment by oliviergenest** [comment]
Thanks, here it is:
![image](https://user-images.githubusercontent.com/47632278/96089976-e056d580-0ec7-11eb-9a2e-75401dc87188.png)

**Comment by oliviergenest** [comment]
Here are some additional infos to better frame the issue: it seems that the `$task['nb_metadata'] > 0` assertion in footer_icon.php returns false.
If I replace the `if($task['nb_metadata'] > 0)' by `if(true)`, the tooltip icon is well displayed and the meta fields are visible:
![image](https://user-images.githubusercontent.com/47632278/96272289-32821e80-0fce-11eb-8c38-1aecc292a61a.png)
Hope this helps!

**Comment by creecros** [comment]
it does, it illustrates to me the conflict. The issue is a conflict with Group_assign.

MetaMagik extends the TaskFinderModel method, `getExtendedQuery()`
Group_assign has over ridden that Model, as well as many others. 
Therefore, the extended query is no longer capable of populating `nb_metadata` property, it's empty. 
Empty is not greater than 0

The issue is not fixable from this plugin, i would have to compensate from Group_assign.

**Comment by creecros** [comment]
Of course, as i go to look into it, I discover, I already compensated, and then take another quick look at your plugin page to determine you are 24 releases behind on Group_assign.

It's important to stay up to date on your plugin versions.

**Comment by oliviergenest** [comment]
Thanks, it works fine now!
We definitely need to improve our way of keeping KB and its plugins up-to-date.
