### ISSUE TITLE
Show field on front of card

### ISSUE THREAD

**Issue by oliviergenest** [creecros/MetaMagik#58]
This is not an issue but a feature suggestion: add an option to make a field visible on the front of the card, as it is done in the "Custom fields" feature of Trello, see below example:
![image](https://user-images.githubusercontent.com/47632278/96009375-dfc72c00-0e40-11eb-8c87-c0c452f1efca.png)
This option could be activated/deactivated for each field.

It would be really useful, e.g. to turn KB into a CRM in which we can see the cost of each opportunity.
Many thanks to consider this feature.

**Comment by oliviergenest** [comment]
Would you agree, in principle, with such feature?
If yes I may find a colleague who could develop it.

**Comment by creecros** [comment]
Seems like a decent feature, and logical request. It would not be too difficult to implement. I have unfortunately, been very unmotivated these days to implement new features on any of my plugins or software, as I simply prefer to utilize my time with other things in life, that are beneficial to my family. Although, I enjoy writing code and figuring things out, spending hours of my time writing code for free is not profitable, and I can't currently  justify it.

**Comment by creecros** [comment]
@oliviergenest 

Actually, this was easier than I thought. 
![image](https://user-images.githubusercontent.com/26339368/96613857-6fe7f400-12cd-11eb-9489-0826a5405f4d.png)

**Comment by oliviergenest** [comment]
Thanks, it works fine !
