### ISSUE TITLE
Ability to edit a custom field's name, scope, required status, on footer status and column

### ISSUE THREAD

**Issue by lionel-bijaoui** [creecros/MetaMagik#62]
First off all, thank you a lot for this awesome plugin !

I was wondering if it could be possible, as an improvement, to be able to edit a custom field.

I understand that changing it type or options might be impossible, but maybe the other properties might be possible to edit ?

It would be nice to be able to change some properties without loosing everything.

Anyway, thank you for your time, have a good day !

**Comment by creecros** [comment]
lot of extra work for such little gain.

If I added it, it would go like this:

- Click edit
- Form pops up
- Edit options, click save

Currently:

- Click remove
- Remake the field
- Click save

I'll leave the request open and maybe one day when I am bored I'll add it, but just don't currently have any motivation to invest time into such a little gain.

**Comment by lionel-bijaoui** [comment]
The main gain would be to keep already set data on existing tasks.

If I set a custom field, then edit some task with that new field, then, later, if I want to fix a typo, or change the name of the custom field, it will be impossible to to without losing the data.

But I understand your position, this is not critical.
Thank you for your response and your time, have a nice day !

**Comment by wucherpfennig** [comment]
Actually this is the only reason why we are not using this plugin. 

Redoing is not the issue. but not loosing data is.

**Comment by creecros** [comment]
I feel like that's a guilt trip. I have no guilt.

data is not lost, even if you remove a field. with a basic understanding of the metadata, you would understand that. 

I understand the ask, and at this moment in time, my very valuable time is limited, so, im sorry I don't have the time today, to make it easier for you, to use my freely provided plugin, that I spent a great deal of time creating, because of the inconvenience of making it simpler for you.

**Comment by creecros** [comment]
you now have the ability to modify custom fields. 

upon doing so, please note, The values you previously had in any field, will remain that previous value. What does this mean? Well, if you had a Custom field of type "Text", and lets say in a certain task there was a value of "MyText", now you change the field to have the type "Number", well, that's not a number, but it will maintain its previous data and visibily show "MyText", even though that's not a number. However, If you were to go edit that particular field, the value would have to be reentered as a Number in this case, else, no modification could be made as it would not conform with a number. It is upon modification or creation, where VALIDATION occurs. 

I urge you to test thoroughly and make sure I didn't miss something. I spent 4 hours, already, and would appreciate not having to spend anymore time testing.

**Comment by creecros** [comment]
Now that I think about it, I need to ensure that we are incapable of renaming a custom field to a duplicate name of another custom field....or that will cause a problem.

**Comment by creecros** [comment]
ok, should be set now, closing, and if you see any issues, just reopen.
