### ISSUE TITLE
Expand vertically / Collapse vertically missing

### ISSUE THREAD

**Issue by korlikiangel** [creecros/MetaMagik#64]
Expand and Collapse vertically in board view disappears after installing this plugin, 

![image](https://user-images.githubusercontent.com/68482509/105359306-99c7f400-5bf7-11eb-88ee-8a8d02d5e4f8.png)

**Comment by creecros** [comment]
Thanks, must be a new feature and the dropdown is an override. 

https://github.com/creecros/MetaMagik/blob/0ba696a70e0d854ef318238d8ecf6e708940c814/Plugin.php#L60

I'll update to the new dropdown as soon as I get a chance.

**Comment by creecros** [comment]
after review, i am pretty sure i didn't need that override. one of the problems with trying to keep a plugin up to date when i don't even use the software anymore, is my memory as to why i did something isn't always there. so, maybe there was a reason for it to begin with, just not sure. anyhow, a quick test and everything seems to be ok with out it. let me know if you find anything else.
