### ISSUE TITLE
Custom fields - Analytics

### ISSUE THREAD

**Issue by korlikiangel** [creecros/MetaMagik#65]
Hi,

Please tell me if it is possible to add a report to the Analytics tab that will sum the values in the custom fields if they are numbers. From a selected time period of created tasks. An example of what this would look like in the image below, thanks in advance for the information.

![image](https://user-images.githubusercontent.com/68482509/106644203-14472b00-658b-11eb-96f0-51a9ccf0451b.png)

**Comment by creecros** [comment]
is your question in reference to, MetaMagik, in its current form?

or, are you just simply asking me if this is possible? 

Currently, no, I have not implemented such a thing. But, yes, it is possible.

**Comment by korlikiangel** [comment]
I have to admit that such a feature would make work much easier, so if such a report is possible, would you consider implementing it in your plugin?

**Comment by creecros** [comment]
between work, play, wife, and kids...I'll look into it. I make no promises.

**Comment by creecros** [comment]
@korlikiangel 

is the criteria, of "Type" being a number, or just look at all the field values and determine of they are numeric?

if have this working, by just looking at all the values and using `is_numeric` as the condition, which will include all numeric values, including values from custom dropdowns. But I could just limit it to Custom fields with the "Type" defined as "Number".

![image](https://user-images.githubusercontent.com/26339368/106786225-4eacd880-661c-11eb-8dee-b7f09dfd261e.png)

I did not do a date range filter, as of yet, already spent more time than I wanted...did you really need the range?

**Comment by creecros** [comment]
The more I think about it, I think it should be based on the data type being a number.

i.e. Number has to be chosen in the Custom field settings:
![image](https://user-images.githubusercontent.com/26339368/106789109-d1836280-661f-11eb-8d33-368aee8f0ef8.png)

**Comment by creecros** [comment]
@korlikiangel 

Master Repo has been updated, test it out, let me know what you think (you will need to install via the master repo files).
https://github.com/creecros/MetaMagik/archive/master.zip

 I'll update the release after your feedback.

**Comment by creecros** [comment]
added one with a date range for creation dates as well, as requested.
![image](https://user-images.githubusercontent.com/26339368/106798260-c0405300-662b-11eb-8a21-2373f4117a14.png)

**Comment by korlikiangel** [comment]
Wow, nie spodziewałem się że zrobisz to tak szybko, bardzo dziękuje za wdrożenie tego rozwiązania, tez uważam że wartości liczbowe będą najlepszym rozwiązaniem w tych raportach. Podczas testowania zauważyłem tylko jedną rzecz, w raporcie gdzie jest możliwość wyboru zakresu dat, musimy wybrać datę utworzenia od dowolnej daty do daty w przyszłości, nie wyświetla wyników jeżeli wybierzemy do dziś lub do wczoraj.

![image](https://user-images.githubusercontent.com/68482509/107010366-8c357100-6796-11eb-9a6b-4d5a1b9f0543.png)

**Comment by creecros** [comment]
![Uploading b680a6e6ce9d64a0903c0a28fa1e75e4-1024x512.png…]()

**Comment by korlikiangel** [comment]
For example, no statistics are displayed if I select dates only for yesterday, or any other single day or range up to yesterday. If I select a range from earlier days to today it works. if I select statistics only for today it does not display the statistics either. However, the statistics for today will be displayed if I select dates from today to tomorrow.

**Comment by creecros** [comment]
I already moved on to a new plugin I was working on, so might be a bit before I can get back to this one. 

it sounds like today, is not necessary today in comparison to the creation time, since in reality, it's in Unix time, so even 1 sec difference would clarify as tomorrow, for example.

**Comment by creecros** [comment]
Exactly what I thought was going on, was going on. I didn't account for 2 things:

1.) Your timezone
2.) Time of the day.

I have corrected the code, to now, account for your timezone, and extend the full day on the `to` field. The `from` field will now account for timezone, but will continue to start at 00:00 hour of the day, since that is when the day begins.

Previously, if I chose today in my `to` field, which today is 2/9/2021, the unix timestamp was:
![image](https://user-images.githubusercontent.com/26339368/107385678-1c3e2800-6ac1-11eb-8e6c-7fd11c2d90ba.png)

with corrected code, the new timestamp is:
![image](https://user-images.githubusercontent.com/26339368/107385764-2f50f800-6ac1-11eb-81f3-4c3a999fc8dc.png)

**Comment by korlikiangel** [comment]
Hi,

Thank you very much for making the changes, I updated the plugin and the first "Custom field total distribution for open tasks" works, but if I try to access the second tab "Custom field total distribution with date range" I get this message, Internal Error: SQL Error: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: ""

**Comment by creecros** [comment]
i missed a commit, should be set now

**Comment by korlikiangel** [comment]
Works like a dream, thanks for your help and commitment.
