### ISSUE TITLE
Keep values of custom fields if one required field is empty

### ISSUE THREAD

**Issue by KanjiCRC** [creecros/MetaMagik#67]
Actual behavior
If we have required fields enabled for task creation and one is left empty once the Save button is pressed all the fields are empty afterwards.

Expected behavior:
If a required field is left empty and the SAVE button is pressed , the rest of the custom fields should keep the old values.

**Comment by creecros** [comment]
@KanjiCRC 

I think that will do it, might want to test it a bit, I am not 100% sure if it covers all the data types.

**Comment by KanjiCRC** [comment]
> @KanjiCRC
> 
> I think that will do it, might want to test it a bit, I am not 100% sure if it covers all the data types.

@creecros From the first test it seems it works for all data types, except the check mark, which is not a big issue

**Comment by creecros** [comment]
@KanjiCRC 

reformatting those values was a nightmare...but i think i got it, checkbox groups appear to work now.
