### ISSUE TITLE
Filters and Searching

### ISSUE THREAD

**Issue by creecros** [creecros/MetaMagik#7]
Filters work now

find tasks that have meta field name = metakey:name
find tasks that have value in any key = metaval:value

want to improve by adding more filters, i.e. find task with value in a certain key, and no, metakey: name metaval:value combined won't work the way i currently have them setup. I know what needs to be done, i'll get to it.

**Comment by creecros** [comment]
https://github.com/kanboard/kanboard/tree/master/libs/picodb

**Comment by TheCloud** [comment]
Want to close this conversation ? I tested filters and I find it very nice.
using metakey:Customer metaval:IBM I could find all tasks belonging to Customer=IBM (if a Customer meta field is added)

**Comment by creecros** [comment]
I was thinking about changing a bit to ilike instead of eq, so that it would find ibm vs IBM as well, and allow wildcards. That said, I tested again, and it was not working for me, so not sure what's going on with it right now. Been busy this weekend, so haven't had a chance to look into it.

**Comment by creecros** [comment]
try now, should work with wildcards.
