### ISSUE TITLE
Edit Fields

### ISSUE THREAD

**Issue by ogalbnafets** [creecros/MetaMagik#70]
Now, if I have to edit fields (their properties), I have to edit them in SQL.

An option to edit them in the settings would pe superb.

Thanks!

**Comment by creecros** [comment]
I do not understand what you mean.

**Comment by ogalbnafets** [comment]
The custom fields I create with the plugins, properties like Options, Scope, Required.

**Comment by creecros** [comment]
ummm....already did.
https://github.com/creecros/MetaMagik/releases/tag/1.5.0
