### ISSUE TITLE
metakey and metaval filters seem not to be working

### ISSUE THREAD

**Issue by bmscmoreira** [creecros/MetaMagik#75]
I am trying to search for specific boards using the filters but the result is not as expected. Example:

- I have a custom field called "Tipo" (of type "check") and possible values A,A1,A2,B and B1;
- I have one board (from now on designated as "A1B1 board") with A1 and B1 in "Tipo" 
- I have one board (from now on designated as "A board") with A in "Tipo" 
- and I have other boards with no values in "Tipo";

If I search for metaval:"A" then A1B1 board shows and A board shows; I was expecting that only A board showed up;
If I search for metaval:"B1" then A1B1 board shows and nothing else; works as expected;
If I search for metaval:"C" then all boards show; I was expecting nothing to show.

I am using Kanboard v 1.2.22.

**Comment by creecros** [comment]
what version of metamagik?

please share visuals, as I'm confused, and not understanding. might just be what you call a board I would call a task, but not sure.

**Comment by creecros** [comment]
assuming when you say board, you mean task.

>If I search for metaval:"B1" then A1B1 board shows and nothing else; works as expected If I search for metaval:"A" then A1B1 board shows and A board shows; I was expecting that only A board showed up

correct, the filter uses "ilike" they both have "A", thus, they both show up. I'm not going to change that, because its a double edge sword. possible to add a filter for exact tho.

>If I search for metaval:"B1" then A1B1 board shows and nothing else; works as expected

correct, as it is the only task with "B1"

>If I search for metaval:"C" then all boards show; I was expecting nothing to show.

agree, ill take a look, but I think that is just how the query works. but we could change that, I have done it before on other filters.  if it finds nothing it just returns everything, sort of like a reset.

**Comment by bmscmoreira** [comment]
Hi. Using version 1.5.0. Please see image below, I think it should clarify. I am searching for the "cfield" custom field using the metaval filter.
Thank you.

![2022-04-19_11-41-45_PM](https://user-images.githubusercontent.com/3017910/164113567-079f33a6-3150-49e5-a7b4-fdb93a4c90e6.gif)

**Comment by creecros** [comment]
ya, that's weird...

**Comment by bmscmoreira** [comment]
Found something: I am using "coverimage" plugin as well - and since it uses a custom field as well, it's affecting the query.

**Comment by creecros** [comment]
that kind of makes sense, and is a good starting point to solve it. Coverimage stores the image ID in the metadata, so, maybe when searching for "A3" there just happens to be a task that has "A3" in the image id? Just a guess, try adding, "Status:Open", in your search query? This is not something I will have time to troubleshoot anytime soon.

**Comment by creecros** [comment]
i say that, but the more i look at it and think about it, it still doesn't make sense, that shouldn't affect it at all...who knows.

**Comment by creecros** [comment]
Try that, report back. I tested on my end.  It now returns nothing, if nothing is found.

**Comment by bmscmoreira** [comment]
Thanks. Works perfectly!
