### ISSUE TITLE
using API with MetaMagic

### ISSUE THREAD

**Issue by Shahin-rmz** [creecros/MetaMagik#76]
Hello,
Thanks for the plugin. It is very useful for me.

Recently, I started to use [Kanboard API](https://docs.kanboard.org/en/latest/user_guide/index.html) with python to automate part of my job.

How ever, for the projects that I use `cusom fields`, I can not create a task with api.
when I delete the custom fields of that project, the api works fine.
I do not get any error so there are no logs.
It just don't work.

Any idea how can I use api when using MetaMagic on a project?
Thanks

**Comment by creecros** [comment]
if metamagik is preventing api then there would be an error log somewhere. I've never had an issue, so I'd just be shooting blindly at a problem that seems to only exist on your end. 

if you have more information, let me know.

**Comment by creecros** [comment]
for reference
https://github.com/creecros/MetaMagik/issues/39

**Comment by creecros** [comment]
produce an error log, and I'll be happy to take a look. the api response would even help.

otherwise, I cant help you.

**Comment by Shahin-rmz** [comment]
Would you please write an example.
I may have syntax problem, and don't know how to mention custom fields in API (with Python).

**Comment by Shahin-rmz** [comment]
> produce an error log, and I'll be happy to take a look. the api response would even help.

That's exactly my problem.
I do not get any errors.
Could you please write a simple example with `required custom field` using Python wrapper, maybe I am doing something wrong.
Thanks

**Comment by Shahin-rmz** [comment]
I can _update_ the `custom fields` when the the task is already made and task_id has been given.
But _creating metadata while making a task_ seems not possible as I can see.

**Comment by creecros** [comment]
I'll test it out when I get time.

**Comment by Shahin-rmz** [comment]
> I dont know python though.
curl will be enough.
just to show how to add metadata while making a new task and I'll be good.

**Comment by creecros** [comment]
if I never get around to this, which I will admit, my time is very limited:
https://github.com/eSkiSo/Subtaskdate

I wrote api commands for this plugin. so you or anyone else could take cues, possibly come up with a solution.

**Comment by creecros** [comment]
can you tell me why you can't?
https://docs.kanboard.org/v1/api/task_metadata_procedures/

**Comment by creecros** [comment]
ok, after re reading this issue, i think my feeble brain has finally understood the issue. 

if you have a custom field in a project that is "required" and you are using api to create a task, you can't.

Now I need to wrap my head around it.

**Comment by creecros** [comment]
Give that a try, use api action "createTaskMeta" to create a task. 

Currently it works exactly as "creatTask" in KB core, but i added a switch so that the TaskCreationModel knows it is an API procedure, and will not try to add any custom fields. 

This does not allow you to add custom fields during task creation through API, but should allow you to create a task at least.

It is untested. so I will be wurprised if it works of that bat, if it does, damn im good at guessing.

**Comment by ulrischa** [comment]
Ok i will try it with the latest from this repo

**Comment by ulrischa** [comment]
I get this error
curl -u "jsonrpc:TOKENHERE" -d "{\"jsonrpc\": \"2.0\", \"method\": \"createTaskMeta\", \"id\": 99999, \"params\": { \"project_id\": 1,  \"owner_id\": 1,\"title\": \"Test\", \"column_id\": 2}}" http://localhost/kanboard/jsonrpc.php
<br />
<b>Fatal error</b>:  Uncaught Error: Class &quot;Kanboard\Plugin\MetaMagik\Api\Procedure\ProjectAuthorization&quot; not found in C:\xampp81\htdocs\kanboard\plugins\MetaMagik\Api\Procedure\NewCreateTaskProcedure.php:26
Stack trace:
#0 [internal function]: Kanboard\Plugin\MetaMagik\Api\Procedure\NewCreateTaskProcedure-&gt;createTaskMeta('Test', 1, '', 2, 1, 0, '', '', 0, 0, NULL, 0, 0, 0, 0, 0, 0, '', Array, '', NULL, NULL)
#1 C:\xampp81\htdocs\kanboard\libs\jsonrpc\src\JsonRPC\ProcedureHandler.php(212): ReflectionMethod-&gt;invokeArgs(Object(Kanboard\Plugin\MetaMagik\Api\Procedure\NewCreateTaskProcedure), Array)
#2 C:\xampp81\htdocs\kanboard\libs\jsonrpc\src\JsonRPC\ProcedureHandler.php(155): JsonRPC\ProcedureHandler-&gt;executeMethod(Object(Kanboard\Plugin\MetaMagik\Api\Procedure\NewCreateTaskProcedure), 'createTaskMeta', Array)
#3 C:\xampp81\htdocs\kanboard\libs\jsonrpc\src\JsonRPC\Request\RequestParser.php(148): JsonRPC\ProcedureHandler-&gt;executeProcedure('createTaskMeta', Array)
#4 C:\xampp81\htdocs\kanboard\libs\jsonrpc\src\JsonRPC\Server.php(372): JsonRPC\Request\RequestParser-&gt;parse()
#5 C:\xampp81\htdocs\kanboard\libs\jsonrpc\src\JsonRPC\Server.php(321): JsonRPC\Server-&gt;parseRequest()
#6 C:\xampp81\htdocs\kanboard\jsonrpc.php(5): JsonRPC\Server-&gt;execute()
#7 {main}
  thrown in <b>C:\xampp81\htdocs\kanboard\plugins\MetaMagik\Api\Procedure\NewCreateTaskProcedure.php</b> on line <b>26</b><br />

**Comment by ulrischa** [comment]
I installed fresh kanboard and new metaMagic folder with all files from master branch here

**Comment by creecros** [comment]
perfect, error code tells me what I forgot, ill update and we can try again.

**Comment by creecros** [comment]
well, im getting stumped. 

mine dies in the task validator. If I bypass the validator, it works fine. at least im close.

**Comment by creecros** [comment]
and then i remembered I overrode the task validator....duh

**Comment by ulrischa** [comment]
I will try it tonight or tomorrow

**Comment by creecros** [comment]
sounds good, I actually tested it this time, so it should be straight.

**Comment by ulrischa** [comment]
Cool!
Thank you very much

**Comment by ulrischa** [comment]
Just tested it: Still not possible to create tasks when MetaMagic is installed. I loaded ZIP here from GitHub.
Runtime:
Version: 1.2.26
PHP Version: 8.1.10
PHP SAPI: apache2handler
HTTP-Client: cURL
OS Version: Windows NT 10.0
Datenbanktreiber: sqlite
Datenbank Version: 3.36.0

**Comment by creecros** [comment]
you have to use the new api action. "createTaskMeta"

**Comment by ulrischa** [comment]
Oh no I used createTask. Thanks
