### ISSUE TITLE
Empty values can be considered a delete

### ISSUE THREAD

**Issue by TheCloud** [creecros/MetaMagik#8]
I don't know if you agree with my vision, but an empty metaval can be considered as not to be saved, so it can be deleted from the database.

Please note that I consider 0 (zero) as non-empty

If I create a metakey with name "Value" and don't enter it, for each task edited/created the empty value is also created in the database, but maybe it should not be.

Let me know your view

**Comment by creecros** [comment]
If it's defined in the settings, it creates the field, and offer's you the ability to enter a value. I could hide empty fields in the summary, is that what you are asking?

**Comment by creecros** [comment]
Think about it like this:
If you leave the task description empty, it is left empty in the database.

I'll take a look and see what I can do though. Hiding empty might be the best I can do, but maybe not. I know I wrote in the code, to force them to be created as empty, and I feel like there was a reason for it.

**Comment by creecros** [comment]
[no_empty_field](https://github.com/creecros/MetaMagik/tree/no_empty_fields) branch.

Test it, make sure it works and is what you had in mind.

**Comment by creecros** [comment]
crap, now I remember why I added it.
When you go to modify the task...the field is non existent to update and you get:
Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 no such column: metamagikkey_Cost

need more time to fix apparently.

**Comment by creecros** [comment]
I'm going to keep empty values, but will hide them whereever there is visual feedback. No one will ever know they exist, unless the litteraly go into the database.

**Comment by creecros** [comment]
empty values are now hidden.
