### ISSUE TITLE
I am unable to select and copy text from metamagic tables in task view

### ISSUE THREAD

**Issue by Chaosmeister** [creecros/MetaMagik#82]
looks like one of the classes `class="connected ui-sortable"` adds `disableSelection` as an eventlistener.  
I can't copy directly from the metamagic values because of this.

There are a few workarounds with some drawbacks:
- Start the selection in the table header - need to filter the copied data afterwards
![image](https://user-images.githubusercontent.com/13346344/177324013-8ead957c-18c8-484c-92c9-0649618d66fb.png)
- Remove the Eventlistener - laborious
- Copy from the edit mask / edit view  - another avoidable step

**Comment by creecros** [comment]
I removed the dragable functionality from the task view, it always annoyed me anyway. You now need to do any Custom Field Re sorting in the settings.

Text is now selectable.
