### ISSUE TITLE
Sales pipeline, amounts and percentages

### ISSUE THREAD

**Issue by DFF-fred** [creecros/MetaMagik#83]
Hi!
I'm trying to find a replacement for Zurmo and struggling. Anyway I'm now off with Kanboard and it's goimg rather ok. We're a small team and have "simple" requirements. Among those we'd like to enter amounts which we can thanks to MetaMagik (we're ok with the things we don't need appearing on the cards...), and also eventually chances of success based on the various stages. 
I've looked into "Automatic actions" to see if i could set a percentage value per stage (column) and eventually... have a value x percent somewhere in a report. Well it does not seem to apply to MetaMagik, so I was wondering if it is possible to do that and how?

Not a big/urgent/I'm gonna die question... but thank you to let me know.
Fred

**Comment by creecros** [comment]
anything is possible with math and knowledge. you know what you want in your mind, but currently in my mind, I'm not exactly following.  So it's hard to tell you how to get there.

**Comment by creecros** [comment]
although, now re reading and thinking about it, it sounds like you want to set values in metamagiks custom fields using automatic actions. 

If so, yes, you can do this. it's going to require you to write your own action to do this, but its very doable and really not that difficult.  I've been going through a rough time with my head at the moment, and have had a constant headache for over a month, if I can get a handle on that I may be able to concentrate enough to help you out. not today tho.

**Comment by creecros** [comment]
for reference 
https://github.com/eSkiSo/Subtaskdate

see api procedures I wrote here, should be a good guide.

**Comment by creecros** [comment]
Added an Action that will update a Custom Field to a specific Value when a Task moves to a Specific Column. Consider it a guide and Example on how to create your own actions using custom fields.

**Comment by DFF-fred** [comment]
Thank you so much, really appreciate.
