### ISSUE TITLE
Cannot unassign tasks when MetaMagik is active

### ISSUE THREAD

**Issue by cornercase** [creecros/MetaMagik#87]
I recently installed MetaMagik 1.5.2 on Kanboard v1.2.22 (later tried with 1.2.26, same behavior demonstrated).  I found that when MetaMagik is active, I cannot unassign a task that has been assigned to a user .  If I create a task without assigning a user, it will be unassigned.  However, once any user has been assigned, I am able to change the assignee to a different user, but can never set the task back to unassigned.  This is in contrast to standard Kanboard behavior, in which a task can be unassigned.  If I attempt to unassign a task, when the task is saved, it remains assigned to the user to which it was previously assigned.

OS:  Ubuntu Server 20.04.03 LTS
PHP version: 7.4
Web server: Apache 2.4
Other details:  external auth against a FreeIPA server is configured

**Comment by creecros** [comment]
are there other plugins invloved?

**Comment by creecros** [comment]
nevermind, i found the issue. 

It's caused by line 36 in this commit:
a1a3b91ba82db29524b56fe8a73e7393b6a8e46a

Not sure why this was added, but I will look into it, and see about a fix.

**Comment by creecros** [comment]
And after further investigation, this is definately the issue. 

![image](https://user-images.githubusercontent.com/26339368/214581516-f731e85b-b80e-4c26-983a-077f91371f90.png)

https://www.php.net/manual/en/function.array-filter.php

**Comment by cornercase** [comment]
Thanks for looking into this, I'm happy to do any testing if it's helpful.
