### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by TheCloud** [creecros/MetaMagik#9]
I was thinking how to manage the export.

Currently Kanboard export feature saves all TAGs into a single CSV cell with comma separated values, so it's very hard to group them using Excel filters.

For Metadata I was thinking to extend the current export table with a column for each metakey.
If Metaval <> empty then it's populated, otherwhise a "null" value is inserted so the CSV is respected.

What do you think ?

**Comment by creecros** [comment]
Im fine with whatever here. Hadn't even thought about it tbh. This something you are going to work on?

**Comment by creecros** [comment]
Columns aren't going to line up either. Actually aren't going to line up if one task has extra meta data defined from the previous portion of the plugin.

**Comment by creecros** [comment]
This now works, just sorting out the columns, I'm making it so it only exports custom fields, not any extra metadata defined somewhere else. This is because, The fields would never lineup with the data without extensive amounts of code, that I'm not really wanting to write.

**Comment by creecros** [comment]
oh, it's in the export branch for testing

**Comment by creecros** [comment]
Works perfectly. Merged to master.
