### ISSUE TITLE
Key-Value from DB with giving tablename,keycolumn,valuecolumn stop working

### ISSUE THREAD

**Issue by SashLi** [creecros/MetaMagik#94]
If you create and try to use a Key-Value from DB with the syntax as described:

> For Key-value from DB: tablename,keycolumn,valuecolumn.

This stop working with KanBaord Version  > 1.2.28

Shows Error in New Ticket GUI: `Internal Error: Invalid identifier: metadatatable` where the field should be shown

**Comment by creecros** [comment]
If you don't know what your doing with that type, you will break it, this is known.
