### ISSUE TITLE
Analytic Controller not works

### ISSUE THREAD

**Issue by Brianfcs98** [creecros/MetaMagik#95]
Hi, I’m using Kanboard with MetaMagik 1.2.22 plugin(I know is a old version), i was trying add date filters to Task Distribution but I see that there are a controller and template doing this. But it does not work.

When I press execute nothing appears.
The problem is that missing some configuration or missing some programming?

**Comment by creecros** [comment]
There is no Metamagik v 1.2.22, analytics wasn't added until v1.4.10

**Comment by creecros** [comment]
Tested works fine.

Make sure you understand what it does, so that you can understand what to expect.
